const number = [
"one",
"two",
"three",
"four",
"five",
"six",
"seven",
"eight",
"nine",
"ten",
"eleven",
"twelve",
"thirteen",
"fourteen",
"fifteen",
"sixteen",
"seventeen",
"eighteen",
"nineteen",
"twenty",
];

const TEST_241016 = [
"plant",
"duck",
"sum",
"real",
"pretend",
"fur",
"feathers",
"scales",
"blue jay",
"ladybug",
"elephant",
"koala",
"spider",
"frog",
"hop",
"crawl",
"shelter",
"grow",
"know",
"cycle",
"hatchling",
"tadpole",
"adult",
"newborn",
"food",
"air",
"water",
];

const plural_lesson1 = { 
"mouse": ["mice", "mouses", "mousees", "micez"],
"child": ["children", "childs", "childes", "childi"],
"goose": ["geese", "gooses", "goosies", "goosen"],
"fox": ["foxes", "foxs", "foxes", "foxen"],
"book": ["books", "bookes", "bookis", "bookies"],
"box": ["boxes", "boxs", "boxies", "boxen"],
"man": ["men", "mans", "manes", "menin"],
"tooth": ["teeth", "tooths", "toothes", "teethen"],
"egg": ["eggs", "egges", "eggis", "eggies"],
"pencil": ["pencils", "penciles", "pencilis", "pencilies"],
"tape": ["tapes", "taps", "tapees", "tapen"],
"glue": ["glues", "gluees", "gluis", "gluies"],
"color": ["colors", "colores", "coloris", "colories"],
"paint": ["paints", "paintes", "paintis", "painties"],
"leg": ["legs", "leges", "leggis", "legies"],
"grass": ["grasses", "grasss", "grassies", "grassen"],
"person": ["people", "persons", "peoples", "persones"],
"leaf": ["leaves", "leafs", "leafes", "leavs"],
"house": ["houses", "hourses", "housis", "housies"],
"bus": ["buses", "busses", "busis", "busies"],
"baby": ["babies", "babys", "babyes", "babien"],
"foot": ["feet", "foots", "footes", "footi"],
"sheep": ["sheep", "sheeps", "sheepes", "sheepies"],
"fish": ["fish", "fishes", "fishs", "fishen"],
};

const TEST_241018 = [
"all",
"down",
"four",
"from",
"her",
"now",
"saw",
"went",
"once",
"ran",
"friends",
"fell",
"dusty",
"dull",
"beautiful",
"butterfly",
"thank",
"dips",
"egg",
"will",
"tell",
"well",
"grass",
"miss",
];

const unit3 = [
"game",
"marble",
"puzzle",
"card",
"doll",
"ball",
"car",
"kite",
"dash",
"rush",
"fish",
"wish",
"ship",
"shop",
"predators",
"prey",
"leap",
"web",
"cast",
"spiral",
];

const lesson1 = [
"leg",
"web",
"hen",
"red",
"let",
"get",
"yet",
"wet",
"made",
"have",
"day",
"look",
"they",
"out",
"fly",
"write",
"every",
"see",
"hear",
"touch",
"smell",
"taste",
"compare",
"observe",
"sort",
"measure",
"pencil",
"pencil case",
"desk",
"chair",
"backpack",
"notebook",
"book",
"leaves",
"exclaimed",
"nest",
"twigs",
"surprise",
"soon",
"warm",
"empty",
"soft",
"feathers",
"you",
"missing",
"thermometer",
"balance",
"measure cup",
"hand lens",
"draw",
"line",
"match",
"tool",
"picture",
"skin",
"things",
"nose",
"learn",
"apple",
"monkey",
"robin",
"cardinal",
"dog",
"food",
"gym",
"boy",
"mom",
"door",
"fireman",
"tiger",
"jungle",
"turkey",
"farm",
"lion",
"giraffe",
"kangaroo",
"cat",
"elephant",
"horse",
"ant",
"zoo",
"where",
"what",
"who",
"which",
"when",
"how",
"library",
"supermarket",
"phone",
"shoes",
"cup",
"umbrella",
];

const lesson2 = [
"down",
"four",
"from",
"her",
"went",
"egg",
"will",
"tell",
"well",
"grass",
"miss",
"paint",
"paper",
"chalk",
"yarn",
"glue",
"tape",
"red",
"yellow",
"blue",
"white",
"black",
"green",
"purple",
"orange",
"pink",
"gray",
"brown",
];

const definition_unit3 = { 
"The part of a plant that grows underground and absorbs water": ["root", "seed", "leaf", "stem"],
"The main body of a tree that supports the branches": ["trunk", "sprout", "fruit", "soil"],
"A small young plant that has just started to grow": ["sprout", "seedling", "ground", "energy"],
"The small hard part of a plant from which a new plant grows": ["seed", "leaf", "root", "bush"],
"The green part of a plant that grows from the stem or branch": ["leaf", "stem", "seed", "fruit"],
"A woody plant that is smaller than a tree and has many stems": ["shrub", "bush", "trunk", "root"],
"The sweet and fleshy product of a plant that contains seeds": ["fruit", "flower", "leaf", "soil"],
"The colorful part of a plant that is often fragrant and attracts insects": ["flower", "fruit", "leaf", "stem"],
"The top layer of the earth where plants grow": ["soil", "ground", "seed", "root"],
"A young plant that has just emerged from a seed": ["seedling", "sprout", "bush", "shrub"],
"The power that makes things move or work": ["energy", "soil", "ground", "fruit"],
};

const words = {
"number": number,
"TEST_241016": TEST_241016,
"plural_lesson1": {"type": "plural", "words": plural_lesson1},
"TEST_241018": TEST_241018,
"unit3": unit3,
"lesson1": lesson1,
"lesson2": lesson2,
"definition_unit3": {"type": "definition", "words": definition_unit3},
}

